spring.application.name=programble-api
spring.profiles.default=local

server.port=${SERVER_PORT:8080}

programble.environment=${PROGRAMBLE_ENV:local}
programble.api.base-path=${PROGRAMBLE_API_BASE_PATH:/api/v1}

management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.info.env.enabled=true

info.app.name=${spring.application.name}
info.app.environment=${programble.environment}
info.api.base-path=${programble.api.base-path}

logging.structured.format.console=${CONSOLE_LOG_STRUCTURED_FORMAT:logstash}
logging.structured.json.add.service=${spring.application.name}
logging.structured.json.add.environment=${programble.environment}
logging.level.root=${ROOT_LOG_LEVEL:INFO}
logging.level.com.programble.api=${APP_LOG_LEVEL:INFO}
